version: '3'

services:
  db:
    container_name: todo-db
    image: postgres:9.6
    ports:
    - 5432:5432
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}  #this is to inject an external variable into yaml files, ${some name}

      # no is hosted in your machine
      # please i'm connecting to a database
      # u're skipping this part
      # after a success we can dockerize the spring boot ok (:
      # we're not in java ): this a yaml keep track of the extensions at the top
      #so i'm going to start the docker and u see that .env properties get injected into it ok
      # is no magic